package com.facturador.facturapro.domain.model

data class TechnicalReportSummary(
    val id: Long,
    val reportNumber: String,
    val reportDate: String,
    val recipientName: String,
    val recipientAddress: String,
    val sellerName: String,
    val status: String,
    val statusLabel: String,
    val pdfPath: String?,
)

data class TechnicalReportDetail(
    val id: Long,
    val reportNumber: String,
    val reportDate: String,
    val fiscalProfileId: Long,
    val sellerName: String,
    val sellerTaxId: String?,
    val sellerAddress: String?,
    val sellerCity: String?,
    val logoPath: String?,
    val clientId: Long?,
    val recipientName: String,
    val recipientTaxId: String?,
    val recipientAddress: String,
    val section1Title: String,
    val section1Content: String?,
    val section2Title: String,
    val section2Content: String?,
    val section3Title: String,
    val section3Content: String?,
    val section4Title: String,
    val section4Content: String?,
    val introText: String?,
    val finalText: String?,
    val notes: String?,
    val status: String,
    val statusLabel: String,
    val pdfPath: String?,
    val verificationCode: String?,
)

data class TechnicalReportDraft(
    val reportNumber: String? = null,
    val reportDate: String,
    val fiscalProfileId: Long,
    val logoPath: String? = null,
    val clientId: Long? = null,
    val recipientName: String,
    val recipientTaxId: String? = null,
    val recipientAddress: String,
    val section1Title: String,
    val section1Content: String? = null,
    val section2Title: String,
    val section2Content: String? = null,
    val section3Title: String,
    val section3Content: String? = null,
    val section4Title: String,
    val section4Content: String? = null,
    val introText: String? = null,
    val finalText: String? = null,
    val notes: String? = null,
    val status: String = "draft",
)

data class TechnicalReportSetting(
    val section1DefaultTitle: String,
    val section2DefaultTitle: String,
    val section3DefaultTitle: String,
    val section4DefaultTitle: String,
    val introText: String?,
    val finalText: String?,
    val reportPrefix: String,
    val nextReportNumber: Int,
    val numberLength: Int,
    val allowManualNumber: Boolean,
    val nextNumberPreview: String,
)
